### ISSUE TITLE
[BUG] setChildren with a element with children

### ISSUE THREAD

**Issue by mstip** [redom/redom#102]
Hi,

think i found another bug ; ). (Sorry for playing around with strange corner cases :D).

The following code
```
const {
  mount,
  el,
  setChildren,
} = redom;

const myElem = el('div');
const mySelect = el('select', [
  el('option', { value: '1' }, 'one'),
  el('option', { value: '2' }, 'two'),
  el('option', { value: '3' }, 'three'),
]);
setChildren(myElem, mySelect);

mount(document.getElementById('app'), myElem);
```
results in this html:
```
<div>
  <select>
    <option value="2">two</option>
  </select>
  <option value="1">one</option>
  <option value="3">three</option>
</div>
```

JSFiddle to play with: [Example](https://jsfiddle.net/nbrunch/woLa381e/)

Am i doing something wrong ?

Cheers 

Marc

**Comment by pakastin** [comment]
No worries, it's just great! Let me see now.....

**Comment by pakastin** [comment]
I agree with you, that **is** really weird 😄

**Comment by pakastin** [comment]
I think I found the issue – just a moment..it's similar in a sense, that it's because of the new recursive `setChildren`.

**Comment by pakastin** [comment]
Fixed now in [v3.10.6](https://github.com/redom/redom/releases/tag/v3.10.6). The issue was that `<select>` is both a node and have `length` property. I had forgotten to break execution here: https://github.com/redom/redom/blob/master/src/setchildren.js#L37

So it was both attached to the DOM but also iterated...

**Comment by pakastin** [comment]
Thanks for letting know! I updated the tests again, so that also this can't happen in the future.

**Comment by pakastin** [comment]
Here's now your example also working with the latest version: https://jsfiddle.net/woLa381e/1/

**Comment by mstip** [comment]
Thanks again for fixing this so fast : ).
If i have some spare time i want start  reading the redom code.
So next time i will send you a pull request ;-).

**Comment by pakastin** [comment]
Check out my talk from HelsinkiJS: https://www.youtube.com/watch?v=0nh2EK1xveg

The basic concept is explaned there quite throughoutly in ~30 minutes 😉

**Comment by pakastin** [comment]
The basic idea is that `el` (`html`/`h`) just creates a regular `HTMLElement` with `document.createElement(tagName)`:
https://github.com/redom/redom/blob/master/src/html.js

**Comment by mstip** [comment]
I already watched it. Great talk and really advanced talk.
But the code base has really grown since than.

**Comment by pakastin** [comment]
..and List for example keeps a lookup table of previous Views, so that it can reuse them

**Comment by pakastin** [comment]
Oh, you did – good!

**Comment by pakastin** [comment]
Well, yeah – `mount` have some lifecycle triggers, which is a bit complex..

**Comment by mstip** [comment]
I would love to see more blog posts or videos about redom in real projects.

**Comment by pakastin** [comment]
`parse-query` basically just parses the `query` part of `el(query)`:
https://github.com/redom/redom/blob/master/src/parse-query.js

**Comment by mstip** [comment]
oh this is also really cool.

**Comment by pakastin** [comment]
Yeah, I should create more posts.. I've been really busy with client projects. I'm using RE:DOM in production in all my client projects, for example [iDiD digital signage](www.idid.fi) (https://idid2.fi/manager and https://idid2.fi/player)

**Comment by mstip** [comment]
cool.
At the moment i have a side project with redom. 
And im trying to convince my boss that we should use it in our next big project.
So some "war stories" would really help.

**Comment by pakastin** [comment]
I have some posts in Medium as well:
https://medium.com/re-dom/master-the-dom-bc1a2a06089b
https://medium.com/re-dom/components-with-static-and-dynamic-content-eb953d56e913
https://medium.com/re-dom/virtual-dom-and-me-70949dcca46d

**Comment by pakastin** [comment]
But yeah, I've actually thought about creating a full stack JavaScript -blog, where I would talk about every aspect of node.js web app. Also client-side.

**Comment by pakastin** [comment]
I could write about RE:DOM as well.

**Comment by pakastin** [comment]
For us the biggest reasons of using RE:DOM instead of major players are:
- Performance
- Memory-efficiency
- Flexibility and control
- Simplicity
- Web standards

Virtual DOM used to be actually quite slow. It's gotten faster, however there's still long stack traces and in certain cases quite bad performance. Also the memory consumption is an issue with virtual DOM, since it creates the whole DOM tree twice (virtual DOM + DOM).

There's also situations where virtual DOM don't know how to update without setting `key` to every element. And if you want to customize the experience, it's harder to do with templating. With RE:DOM you can just create and control regular HTML elements how you like and call it a day.

It's also easier to debug issues, when the codebase is small and stack traces are short.

Our digital signage players for example need to run in low-powered and low-memory devices, where you need to drip every performance you can get out of your code. And transitions need to be controlled precisely so that there's no hickups. I have custom requestAnimationFrame loops etc in place there, which might be quite hard to do with virtual dom.

Also everytime we want to include new web standards features (like web components), it's possible with RE:DOM because you create just regular DOM elements. Also integrations with 3rd party libraries are really simple, since you don't need to worry about virtual dom messing things up. Try using google maps with virtual dom for example, without google-map-react or similar..

**Comment by pakastin** [comment]
Oh, and with others I've had problematic dealing with templates. They are really restricting of what you can do. With RE:DOM there really is no limits because it's all just web standards, you can even create games with it really easily.
