### ISSUE TITLE
URL-based routing

### ISSUE THREAD

**Issue by joedakroub** [redom/redom#113]
First of all, thank you for such an elegant and simple library. I really like the concepts presented here.

Are there any plans to offer a URL-based router using the History API or would it be better to create a Page class that uses the lifecycle methods to accomplish this?

**Comment by pakastin** [comment]
Hi and thanks! 👍

Actually right now I'm thinking of _reducing_ things from the next major version, to make RE:DOM even more compact, fast and extensible.

What comes to URL routers, even though I like using regexp-based routers in express.js for example, it doesn't make that much sense in the frontend, since mostly you just change a visual router and that's it. Not to mention the definitions are usually not flat, as they tend to be in the backend.

However nothing prevents a third party to create an extension of the `Router` for example and I'm happy to add that under [`github.com/redom/`](https://github.com/redom), if wanted.

I'm using History API (or hash) myself something like this:
```javascript
/* 
  /:section/:id/:subsection/:subid
*/
const [ section, id, subsection, subid ] = location.pathname.split('/');
// const [ section, id, subsection, subid ] = location.hash.slice(1).split('/');

router.update(section, { section, id, subsection, subid });
```

Do you have a specific use case in mind I could take a look?

**Comment by joedakroub** [comment]
Thanks for the compliment, I'm glad you like my site! 😀

I totally get your rationale for streamlining the library and agree with making things more extensible and opt-in.

I also think creating a different client-side Router may make the most sense. I'm thinking mostly about building progressive web apps that have statically rendered pages and a single page app that loads on top. Client-side routing with URLs is ideal because it follows web standards and handles cases of page reloads, bookmarking etc.

I may create such a router and link component that would handle this scenario. I also thought that creating a base Page component that leveraged 'onmount'/'onunmount' could also cleanly achieve what I'm looking to do.

If I end up creating I new router class, I'd be happy to send it your way.

Thank you again for the quick response and for creating a really lovely library. I watched the presentation where you live-coded the MVP view library and was both impressed by your ability to do that live 👍🏽 and by the clear thinking that you put into creating it.

**Comment by pakastin** [comment]
I will close this. Requested and good feature, but will make a great separate helper 😎
