### ISSUE TITLE
List item instantiation hard coded

### ISSUE THREAD

**Issue by katywings** [redom/redom#148]
At the moment the instantiation of list items is hard coded in ListPool:
https://github.com/redom/redom/blob/master/esm/listpool.js#L37

I would like to modify the list item creation with a custom factory, basically as an example allowing a list to have different classes for different items and instantiating the items with custom parameters.

Not sure about how this could look like if it was extended in redom but my first idea was:

```
// Should obviously be defined in the ListPool class ;)
listPool.createView = function(initData, item, i, data)  {
  return new this.View(initData, item, i, data)
}
```

Then the listPool.update could use this function for the view creation. So for customization one could just replace the createView method.

Atm I wrap my view class with an other "proxy" class which can decide what class i actually want to use for this list item :D

Edit: Oh and it could be even implemented in a way, so that createView is in update only used if its defined - so that no extra function call has to happen in update when its not needed :)

**Comment by bluenote10** [comment]
I was wondering about that as well, but doesn't the update logic require lists to be homogeneous? With homogeneous lists, `update` can be called on any item safely because all components are the same. If the list is heterogeneous, say it has components A and B, the (non keyed) reconciliation may have to change an A to a B, which cannot be done by just updating A.

**Comment by katywings** [comment]
@bluenote10: After looking at the code I dont think there really is a good generalization for heterogeneous items
