### ISSUE TITLE
CSS :hover

### ISSUE THREAD

**Issue by perry-mitchell** [redom/redom#174]
I may have missed this in the docs - apologies if I did - but I don't see any way to set CSS states on elements, when using `setStyle`. Ideally I'd like to be able to do this:

```javascript
setStyle(hello, {
  color: "green",
  ":hover": {
    color: "red
  }
});
```

Any ideas? Should I just make a low-level wrapper for hover states?

**Comment by Leeingnyo** [comment]
`setStyle()` is helper function for editing inline style of element. the pseudo classes like `:hover` aren't set by inline style.
see [this stackoverflow answer](https://stackoverflow.com/questions/14141374/using-css-before-and-after-pseudo-elements-with-inline-css/20288572) for more information please.

if you want to use dynamic hovering color,
how about using [css variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)?

```css
/* in css */
.hello:hover {
  color: var(--hover-color);
}
```

```js
/* in js */
setStyle(hello, {
  color: green,
  '--hover-color': red
});
```

I didn't test this code working fine..

for IE, since IE dosen't support css variables, you should make some classes for hovering color... or generate classes with js

**Comment by perry-mitchell** [comment]
Thanks @Leeingnyo - Yes after I checked the source I found that it is indeed just a wrapper for the `style` attribute.

It's just that when you're writing styles with redom, it's nice to think that you could operate on a more complete level with states supported as well. Of course this might bloat the codebase a bit but it's a pretty common thing to need when building UIs.

I'll close this as it's been answered.
